user_input1 = input("What is your favorite animal?\n:  ")
user_input2 = input("why is it your favorite animal?\n: ")
user_input3 = habitat = input ("where do they live?\n: ")
user_input4 = color = input ("what color are they?\n: ")
user_input5 = other_reasons = input("any other reasons?\n: ")
print( "your favorite animal is "+ user_input1 +" because " + user_input2 + "." + " They live in " + habitat + "." + " they are " + color + ". " + other_reasons + " " +"Are other reasons why" + user_input1  +" is your favorite animal.")